<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\ImageCORRECT.png" />
    <None Remove="Assets\ImageERROR.png" />
    <None Remove="Assets\QuizForgeSplashScreen.png" />
    <None Remove="Assets\SoundCorrectAnswer.wav" />
    <None Remove="Assets\SoundIncorrectAnswer.wav" />
    <None Remove="Assets\SoundMusic.wav" />
    <None Remove="Assets\SoundSplashScreen.wav" />
    <None Remove="Assets\SoundStartConfig.wav" />
    <None Remove="Assets\SoundVictory.wav" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Themes\" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\QuizForgeSplashScreen.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Content Include="Assets\ImageCORRECT.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\ImageERROR.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\SoundCorrectAnswer.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\SoundIncorrectAnswer.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\SoundMusic.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\SoundSplashScreen.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\SoundStartConfig.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\SoundVictory.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
